name: Deploy Portfolio

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: [ self-hosted, hostinger ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build & deploy with Docker Compose
        working-directory: ${{ github.workspace }}
        run: |
          docker compose down --remove-orphans
          docker compose up -d --build --remove-orphans
